//! Errors that escape each executable command after CLI conversion.
//!
//! Shared entries cover argument parsing and opening the store. Keep command-specific
//! entries explicit: similar operations can catch different failures or read different
//! payloads. See docs/plans/help-contracts.md for the audit boundaries.

use crate::{CliError, invalid_input};

/// Returns public error codes, excluding failures returned as successful receipts.
#[expect(
    clippy::too_many_lines,
    clippy::match_same_arms,
    reason = "explicit command entries keep error reachability reviewable"
)]
pub(super) fn for_command(command: &str) -> Result<Vec<&'static str>, CliError> {
    if command == "security explain" {
        return Ok(vec!["INVALID_INPUT"]);
    }
    let specific: &[&str] = match command {
        "project init" => &["INVALID_ID"],
        "project revision" => &["INVALID_ID", "PROJECT_NOT_FOUND"],
        "project rebuild" => &["INVALID_ID", "PROJECT_NOT_FOUND"],
        "project view" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "INVALID_SOURCE",
            "INVALID_POLICY_EVALUATION",
            "PAYLOAD_NOT_FOUND",
        ],
        "project delta" => &["INVALID_ID", "PROJECT_NOT_FOUND"],
        "project batch" => &["INVALID_ID"],
        "project authority list" => &["INVALID_ID", "PROJECT_NOT_FOUND"],
        "project authority grant" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "project authority revoke" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "project revalidation list" => &["INVALID_ID"],
        "project revalidation run" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "COMPILER_UNAUTHORIZED",
            "NON_CAUSAL_HISTORY",
            "MISSING_EVIDENCE",
            "COMPILER_INPUT_BUDGET",
            "COMPILER_OUTPUT_BUDGET",
            "INVALID_COMPILER_RESPONSE",
            "COMPILER_ADAPTER_ERROR",
        ],
        "project revalidation resolve" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "REVALIDATION_RUN_INELIGIBLE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        "issue capture" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "COMPILER_REQUIRED",
            "AUTHORITY_BUSY",
            "IO_ERROR",
            "COMPILER_ADAPTER_ERROR",
            "INVALID_FIXTURE",
            "SERIALIZATION_ERROR",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "STALE_PROVIDER_OBSERVATION",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "issue import-fixture" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "INVALID_FIXTURE",
            "IO_ERROR",
            "SERIALIZATION_ERROR",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "STALE_PROVIDER_OBSERVATION",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "issue view" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "INVALID_SOURCE",
            "INVALID_POLICY_EVALUATION",
            "PAYLOAD_NOT_FOUND",
        ],
        "inbox subscribe" => &["INVALID_ID", "INVALID_INBOX_ACKNOWLEDGEMENT"],
        "inbox poll" => &["INVALID_ID", "INVALID_INBOX_ACKNOWLEDGEMENT"],
        "inbox show" => &["INVALID_ID"],
        "inbox ack" => &["INVALID_ID", "INVALID_INBOX_ACKNOWLEDGEMENT"],
        "show" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "OBJECT_NOT_FOUND",
            "CANDIDATE_NOT_FOUND",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        "source show" => &["INVALID_ID", "SOURCE_NOT_FOUND", "PAYLOAD_NOT_FOUND"],
        "source compilation-policy" => &["INVALID_ID", "BINDING_NOT_FOUND"],
        "source compilation-policy set" => &[
            "INVALID_ID",
            "BINDING_NOT_FOUND",
            "PROJECT_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "source assertions" => &["INVALID_ID", "PAYLOAD_NOT_FOUND"],
        "source apply" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "ASSERTION_RUN_INELIGIBLE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "source compile" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "INVALID_COMPILATION",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "COMPILER_UNAUTHORIZED",
            "COMPILER_CONTEXT_REQUIRED",
            "NON_CAUSAL_HISTORY",
            "MISSING_EVIDENCE",
            "COMPILER_INPUT_BUDGET",
            "COMPILER_OUTPUT_BUDGET",
            "INVALID_COMPILER_RESPONSE",
            "COMPILER_ADAPTER_ERROR",
        ],
        "source require" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "INVALID_COVERAGE_PROMOTION",
            "POLICY_INPUT_CONFLICT",
            "POLICY_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "source purge" => &["INVALID_ID", "INVALID_SOURCE", "INVALID_PURGE"],
        "source purge-audit" => &["INVALID_ID", "PURGE_AUDIT_NOT_FOUND", "PAYLOAD_NOT_FOUND"],
        "source replay" => &[
            "INVALID_ID",
            "UNSUPPORTED_REPLAY_VERSION",
            "COMPILER_CONTEXT_REQUIRED",
            "COMPILER_EXPANSION_REFERENCE",
            "COMPILER_EXPANSION_LOOP",
            "NON_CAUSAL_HISTORY",
            "MISSING_EVIDENCE",
            "COMPILER_INPUT_BUDGET",
            "COMPILER_OUTPUT_BUDGET",
            "INVALID_COMPILER_RESPONSE",
            "COMPILER_ADAPTER_ERROR",
        ],
        "compilation list" => &["INVALID_ID", "PROJECT_NOT_FOUND"],
        "compilation show" => &["INVALID_ID", "PROJECT_NOT_FOUND"],
        "compilation context" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "INVALID_COMPILATION",
            "PAYLOAD_NOT_FOUND",
        ],
        "compilation expand" => &[
            "INVALID_ID",
            "PROJECT_NOT_FOUND",
            "COMPILER_UNAUTHORIZED",
            "COMPILER_EXPANSION_REFERENCE",
            "COMPILER_EXPANSION_LOOP",
            "COMPILER_EXPANSION_ROUND_BUDGET",
            "NON_CAUSAL_HISTORY",
            "MISSING_EVIDENCE",
            "COMPILER_INPUT_BUDGET",
            "COMPILER_OUTPUT_BUDGET",
            "INVALID_COMPILER_RESPONSE",
            "COMPILER_ADAPTER_ERROR",
        ],
        "candidate list" => &["PROJECT_NOT_FOUND"],
        "candidate show" => &[
            "CANDIDATE_NOT_FOUND",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        "candidate accept" => &[
            "PROJECT_NOT_FOUND",
            "CANDIDATE_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "candidate reject" => &[
            "PROJECT_NOT_FOUND",
            "CANDIDATE_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "candidate correct" => &[
            "PROJECT_NOT_FOUND",
            "CANDIDATE_NOT_FOUND",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "decision create" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "question create" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "question resolve" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "finding create" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "finding resolve" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "hypothesis create" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "claim create" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "task request" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
        ],
        "task accept" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        "task defer" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        "task start" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        "task complete" => &[
            "PROJECT_NOT_FOUND",
            "SOURCE_CONFLICT",
            "INVALID_SOURCE",
            "POLICY_INPUT_CONFLICT",
            "INVALID_POLICY_EVALUATION",
            "POLICY_ERROR",
            "PAYLOAD_NOT_FOUND",
        ],
        _ => return Err(invalid_input("command has no help error contract")),
    };
    // Store::open can reject the schema, fail I/O, or encounter corrupt migration data.
    let mut errors = vec![
        "INVALID_INPUT",
        "UNSUPPORTED_SCHEMA",
        "STORAGE_ERROR",
        "CORRUPT_HISTORY",
    ];
    errors.extend(specific);
    Ok(errors)
}
