[package]
name = "merl-policy"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
merl-core = { path = "../merl-core" }
merl-store = { path = "../merl-store" }
sha2.workspace = true
time.workspace = true

[lints]
workspace = true
